### ISSUE TITLE
[Editing] Resolve Open Comments from Review

### ISSUE THREAD

**Issue by Tazinho** [Tazinho/Advanced-R-Solutions#168]
#### 1. Introduction
No exercises

#### 2. Names and values
- [x] Included feedback from #164

#### 3. Vectors
- [x] Included feedback from #165
    - Lists ex 3: Compare and contrast c() and unlist() when combining a date and date-time into a single vector.
      - => Passed to Hadley (#228)

#### 4. Subsetting
- [x] Included feedback from #166

#### 5. Control flow
- [x] Included feedback from #169

#### 6. Functions
- [x] Included feedback from #170
  - [[optional]] 3.1 What important property of && makes x_ok() work?...
    - => passed to Hadley (#228)
  - [ ] 5.5 We can use on.exit() to implement a simple version of capture.output(). ... 
    - => passed to Hadley (#228)

#### 7. Environments
- [x] Included feedback from #177

#### 8. Conditions
- [x] Included feedback from #179

#### 9. Functionals
- [x] Included feedback from #180

#### 10. Function factories
- [x] Included feedback from #182
  - [[ optional ]] 2.2 Base R contains two function factories, approxfun() and ecdf(). Read their documentation and ...
    - => passed to Hadley (#228)

#### 11. Function operators
- [x] Included feedback in #183

#### 12. Base types
No exercises

#### 13. S3
- [X] Included feedback in #189
  - [ ] 5.1 How does [.Date support subclasses? How does it fail to support subclasses? ... 
    - => passed to Hadley (#228)

#### 14. R6
- [X] Included feedback in #191

#### 15. S4
- [x] Included feedback in #229

#### 16. Trade-offs
No exercises

#### 17. Big picture
No exercises

#### 18. Expressions
- [x] Included feedback from #192

#### 19. Quasiquotation
- [x] Included feedbackon from #196 

#### 20. Evaluation
- [x] Included feedback from #197

#### 21. Translating R code
- [x] Included feedback in #230
- [x] Included feedback: need to revisit, see #198.
  - [ ] 2.2 Complete the DSL to support all the functions that plotmath supports. ...
    - => passed to Hadley (#228)

#### 22. Debugging
No exercises

#### 23. Measuring performance
- [x] Included feedback in #231
  - [ ] 1.1 Code takes ages to run and we don't really have an idea how to move forward
    - => passed to Hadley  (#228)

#### 24. Improving performance
- [x] Included feedback in #232
  - [[optional] 1.3 List four functions (not just those in base R) that convert a string into a date time object. What are ...
    - => passed to Hadley (#228)
  - [ ] 2.3 Can you make a faster version of table() for the case of an input of two integer vectors with no ... 
    - => passed to Hadley (#228)

#### 25. Rewriting R code in C++
- [x] Included feedback in #233

**Comment by henningsway** [comment]
Hey Malte,
was denkst du zu diesem Issue? Wollen wir es aktualisieren u. behalten oder eher schließen? Ich glaube ne Struktur für die offenen Todos ist grundsätzlich gut, aber irgendwie schreckt mich dieses Issue gerade auch etwas ab. :).

Was meinst du?

**Comment by Tazinho** [comment]
Vlt können wir es umbenennen in „Resolving Hadleys Comments“ oder so, wofür es eigentlich gedacht war.
